Repository qreater/Tartarus, pull requests merged in 2024-08, with the labels that each got.

#6 feat(startup): built `internal_cft` table for building APIs
  app/utils/config/conf.py
  app/utils/config/queries.py
  app/utils/data/datasource.py
  tests/integration_tests/test_datasource.py
  tests/unit_tests/test_datasource.py
Labels: enhancement

#11 fix(general): clean-up for `ConfigDefinition` code
  app/utils/config_definitions/validations.py
  tests/test_main.py
Labels: bug

#12 fix(SQL): using parameterized queries to prevent SQL Injection
  app/utils/config_definitions/queries.py
  app/utils/config_definitions/utils.py
  app/utils/data/data_source.py
  tests/unit_tests/test_config_definition.py
  tests/unit_tests/test_data_source.py
Labels: bug, enhancement

#8 feat(api): built create `ConfigDefinition` API and utils, tests
  app/api/v1/__init__.py
  app/api/v1/config_definition.py
  app/models/config_definition.py
  app/utils/config/__init__.py
  app/utils/config/conf.py
  app/utils/config/queries.py
  app/utils/config_definitions/__init__.py
  app/utils/config_definitions/queries.py
  app/utils/config_definitions/utils.py
  app/utils/config_definitions/validations.py
  app/utils/data/data_source.py
  main.py
  poetry.lock
  pyproject.toml
  tests/integration_tests/test_config_definition.py
  tests/integration_tests/test_data_source.py
  tests/test_main.py
  tests/unit_tests/config_definition/__init__.py
  tests/unit_tests/config_definition/test_create.py
  tests/unit_tests/config_definition/test_delete.py
  tests/unit_tests/config_definition/test_list.py
  tests/unit_tests/config_definition/test_read.py
  tests/unit_tests/config_definition/test_update.py
  tests/unit_tests/test_data_source.py
Labels: enhancement

#19 fix(config-definition): remove primary_key explicit field
  app/api/v1/config_definition.py
  app/models/config_definition.py
  app/utils/config_definitions/queries.py
  app/utils/config_definitions/utils.py
  app/utils/config_definitions/validations.py
  app/utils/data/data_source.py
  app/utils/data/queries.py
  tests/integration_tests/test_config_definition.py
  tests/unit_tests/config_definition/test_create.py
  tests/unit_tests/config_definition/test_update.py
  tests/unit_tests/test_data_source.py
Labels: bug

#20 feat(tests): re-factor testing variable storage
  LICENSE
  app/utils/config_definitions/utils.py
  app/utils/config_definitions/validations.py
  tests/unit_tests/config_definition/payloads/__init__.py
  tests/unit_tests/config_definition/payloads/payload_extractor.py
  tests/unit_tests/config_definition/payloads/payloads.json
  tests/unit_tests/config_definition/test_create.py
  tests/unit_tests/config_definition/test_delete.py
  tests/unit_tests/config_definition/test_list.py
  tests/unit_tests/config_definition/test_read.py
  tests/unit_tests/config_definition/test_update.py
Labels: bug, enhancement

#23 feat(deploy): constructed `Dockerfile` for the application
  .github/workflows/ci.yaml
  backend/.header-config.txt
  backend/.pre-commit-config.yaml
  backend/app/__init__.py
  backend/app/api/__init__.py
  backend/app/api/v1/__init__.py
  backend/app/api/v1/config_definition.py
  backend/app/models/__init__.py
  backend/app/models/config_definition.py
  backend/app/utils/__init__.py
  backend/app/utils/config/__init__.py
  backend/app/utils/config/conf.py
  backend/app/utils/config_definitions/__init__.py
  backend/app/utils/config_definitions/queries.py
  backend/app/utils/config_definitions/utils.py
  backend/app/utils/config_definitions/validations.py
  backend/app/utils/data/__init__.py
  backend/app/utils/data/data_source.py
  backend/app/utils/data/queries.py
  backend/main.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/__init__.py
  backend/tests/integration_tests/__init__.py
  backend/tests/integration_tests/test_config_definition.py
  backend/tests/integration_tests/test_data_source.py
  backend/tests/test_main.py
  backend/tests/unit_tests/__init__.py
  backend/tests/unit_tests/config_definition/__init__.py
  backend/tests/unit_tests/config_definition/payloads/__init__.py
  backend/tests/unit_tests/config_definition/payloads/payload_extractor.py
  backend/tests/unit_tests/config_definition/payloads/payloads.json
  backend/tests/unit_tests/config_definition/test_create.py
  backend/tests/unit_tests/config_definition/test_delete.py
  backend/tests/unit_tests/config_definition/test_list.py
  backend/tests/unit_tests/config_definition/test_read.py
  backend/tests/unit_tests/config_definition/test_update.py
  backend/tests/unit_tests/test_data_source.py
  devops/Dockerfile
  devops/docker-compose.yaml
Labels: documentation, enhancement
