Repository qreater/Tartarus, pull requests merged in 2025-01, with the labels that each got.

#56 feat(tartarus-lib): developing and publishing to PyPi
  .github/workflows/ci.yaml
  .github/workflows/pypi-publish.yaml
  backend/app/utils/config_definitions/utils.py
  library/.header-config.txt
  library/.pre-commit-config.yaml
  library/README.md
  library/__init__.py
  library/pyproject.toml
  library/tartarus_lib/__init__.py
  library/tartarus_lib/clients/__init__.py
  library/tartarus_lib/clients/base.py
  library/tartarus_lib/clients/config.py
  library/tartarus_lib/clients/config_definition.py
  library/tartarus_lib/core.py
  library/tartarus_lib/exceptions.py
  library/tests/__init__.py
  library/tests/conftest.py
  library/tests/entity_tests/test_config.py
  library/tests/entity_tests/test_config_definition.py
  library/tests/payloads/payload_extractor.py
  library/tests/payloads/payloads.json
  library/tests/test_client.py
Labels: enhancement

#60 feat(tartarus-lib): introducing dynamic versioning, workflows
  .github/workflows/pypi-publish.yaml
  library/poetry.lock
  library/pyproject.toml
  library/tartarus_lib/clients/config_definition.py
Labels: enhancement

#62 fix(build): dynamic versioning configuration for CI
  .github/workflows/ci.yaml
  .github/workflows/pypi-publish.yaml
Labels: bug

#64 feat(devops): building and configuration of helm chart
  .gitignore
  devops/tartarus-helm/Chart.yaml
  devops/tartarus-helm/templates/cm.yaml
  devops/tartarus-helm/templates/deploy.yaml
  devops/tartarus-helm/templates/svc.yaml
  devops/tartarus-helm/values.yaml
Labels: enhancement

#58 feat(docs): Initial Documentation for Tartarus
  .github/workflows/docs.yaml
  backend/app/api/v1/config.py
  devops/docker-compose.yaml
  docs/additional-info/cicd.mdx
  docs/additional-info/database-design.mdx
  docs/additional-info/error-handling.mdx
  docs/additional-info/tech-stack.mdx
  docs/api-reference/authorization.mdx
  docs/api-reference/config-definition.mdx
  docs/api-reference/config.mdx
  docs/api-reference/openapi.json
  docs/assets/background-dark.webp
  docs/assets/banner.webp
  docs/assets/dark-banner.webp
  docs/assets/favicon.svg
  docs/assets/logo.svg
  docs/deployment/docker.mdx
  docs/deployment/introduction.mdx
  docs/deployment/kubernetes.mdx
  docs/introduction.mdx
  docs/library/config-api.mdx
  docs/library/configdef-api.mdx
  docs/library/introduction.mdx
  docs/mint.json
  docs/quick-start.mdx
  docs/testing/introduction.mdx
  docs/testing/testing-approach.mdx
Labels: documentation

#66 feat(app): enabled cross-origin resource access for tartarus
  backend/main.py
Labels: enhancement
